services:
  db:
    image: postgres:17
    container_name: Exposure
    restart: always
    environment:
      POSTGRES_DB: exposure_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exposure
      PGTZ: 'Europe/Kyiv'
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
